# Generated by Django 4.2.19 on 2025-03-27 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_score',
            field=models.IntegerField(blank=None, default=0),
        ),
        migrations.CreateModel(
            name='UserFriendMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
